module.exports = {
  int: "INTEGER_TYPE",
  intArray: "INTEGER_ARRAY_TYPE",
  strArray: "STRING_ARRAY_TYPE",
  boolArray: "BOOLEAN_ARRAY_TYPE",
  floatArray: "FLOAT_ARRAY_TYPE",
  float: "FLOAT_TYPE",
  bool: "BOOLEAN_TYPE",
  str: "STRING_TYPE",
  void: "VOID_TYPE",
  const: "CONSTANT",
  func: "FUNCTION",
  print: "NATIVE_FUNCTION",
  split: "NATIVE_FUNCTION",
  random: "NATIVE_FUNCTION",
  Number: "NATIVE_FUNCTION",
  String: "NATIVE_FUNCTION",
  sleep: "NATIVE_FUNCTION",
  pow: "NATIVE_FUNCTION",
  floor: "NATIVE_FUNCTION",
  len: "NATIVE_FUNCTION",
  ask: "NATIVE_FUNCTION",
  return: "FUNCTION_RETURN",
  loop: "FOR_LOOP",
  if: "IF_BLOCK",
  break: "BREAK_EXEC",
  while: "WHILE_LOOP_DECLARATION"
};
