module.exports = {
  "=": "EQUALS",
  ";": "SEMICOLON",
  "+": "PLUS_OPERATOR",
  "-": "MINUS_OPERATOR",
  "*": "MULT_OPERATOR",
  "/": "DIV_OPERATOR",
  "%": "REST_OPERATOR",
  "(": "OPEN_PARENT",
  ")": "CLOSE_PARENT",
  "{": "OPEN_BRACKET",
  "}": "CLOSE_BRACKET",
  ".": "DOT",
  ",": "COMMA",
  "[": "OPEN_SQUARE_BRACKET",
  "]": "CLOSE_SQUARE_BRACKET",
  "==": "EQUAL_OPERATOR",
  "!=": "NOT_EQUAL_OPERATOR",
  "&&": "AND_OPERATOR",
  "||": "OR_OPERATOR",
  ">": "GT_OPERATOR",
  "<": "LT_OPERATOR",
  ">=": "GTE_OPERATOR",
  "<=": "LTE_OPERATOR"
};